### ISSUE TITLE
Adding entity_unleash events

### ISSUE THREAD

**Issue by malonnnn** [EngineHub/CommandHelper#1186]
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityUnleashEvent.html

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerUnleashEntityEvent.html

Just wondering if we could get these added at some point.

Thank you!

**Comment by malonnnn** [comment]
I just noticed the tag "good first issue", which is obviously a hint that you'd like to get people to contribute.

I'd be willing to contribute, but I haven't touched java in more than 10 years since college. I don't touch real programming languages ever, and I'd have no idea what I'm doing.

So my question is: Does "good first issue" target people like me, who don't even understand the "static" keyword, and haven't touched OOP stuff in literally a decade. I don't even know how to set up the IDE. Are you willing to teach? Or is this aimed at people who are at least a little competent?

**Comment by LadyCailin** [comment]
I’m more than happy to work through it with you, if you’re willing to learn, and are willing to put the effort into learning. The tag is meant to state that it’s fairly straightforward of a task, and is a fairly isolated component that doesn’t require to much knowledge of the entire project to contribute to, you just need to know a small slice. 

For this issue in particular, it should be quite easy, since both events and functions that are straightforward tend to be able to be copied from existing ones and then modified, so I think in this case, it’s an exceptionally good first issue. Let’s get up on discord, and get you started if you want.

**Comment by malonnnn** [comment]
Has it really been 18 days already? I'm sorry about that. I knew I missed my initial deadline, wanted to start a couple weeks ago. I'm aiming for this weekend again.

**Comment by LadyCailin** [comment]
Added with #1227
